### ISSUE TITLE
Improve the aesthetics of the level up animation

### ISSUE THREAD

**Issue by mona12rst** [mona12rst/AlkmaarMania#264]
add confetti animation to screen once a level up happens
fix the image blur and resolution
2 hours : @abbydiode

**Comment by abbydiode** [comment]
Can @Zarmina take this one? I'm definitely no designer.

**Comment by mona12rst** [comment]
works for the most part, will leave the issue open to fix a few small position issues with it. it also pops up on level 1. (on load) it shouldnt

**Comment by abbydiode** [comment]
> works for the most part, will leave the issue open to fix a few small position issues with it. it also pops up on level 1. (on load) it shouldnt

Please clarify which small issues you have encountered, the position property has been entirely removed from the animation, so any incorrect positioning would be related to the HUD design.

**Comment by mona12rst** [comment]
> > works for the most part, will leave the issue open to fix a few small position issues with it. it also pops up on level 1. (on load) it shouldnt
> 
> Please clarify which small issues you have encountered, the position property has been entirely removed from the animation, so any incorrect positioning would be related to the HUD design.

its not really a big issue about the looks. it just looks a little off because it goes a little out from the side of the screen, probably can be fixed in a second. so not a big deal.
but the level 1 pop up should be removed.

**Comment by abbydiode** [comment]
> > > works for the most part, will leave the issue open to fix a few small position issues with it. it also pops up on level 1. (on load) it shouldnt
> > 
> > 
> > Please clarify which small issues you have encountered, the position property has been entirely removed from the animation, so any incorrect positioning would be related to the HUD design.
> 
> its not really a big issue about the looks. it just looks a little off because it goes a little out from the side of the screen, probably can be fixed in a second. so not a big deal. but the level 1 pop up should be removed.

What do you mean by level 1 pop up exactly?
