### ISSUE TITLE
Social layer completion

### ISSUE THREAD

**Issue by mona12rst** [mona12rst/AlkmaarMania#395]
make a template for sharing that includes:
current state of happiness index/sustainability.
current streak of minigames
come play with me!
share it!

implementation of the sharing button/sharing functionality.

: @abbydiode  : 16 hours

**Comment by abbydiode** [comment]
> 08/06/2022 the discord sdk is blocking this pr from merging. we can not just remove a feature that has been shown as full and functional to the stakeholders by implementing another one that we have also promised before. so effectively not working on main branch.

The Discord SDK will not work for mobile, it literally does not work. As an alternative solution to this I have implemented native sharing, which also supports sharing to Discord.

**Comment by mona12rst** [comment]
there is no button on the screen for me to be able to share.
